[package]
name = "key-set"
version = "0.1.0"
edition = "2018"

[dependencies]
ark-serialize = { version = "0.3.0", features = ["derive"] }
bincode = "1.3.3"
commit = { git = "ssh://git@github.com/SpectrumXYZ/commit.git", rev = "f48cd52c59755eade0605111826eef3df6abdcf8" }
itertools = "0.10.1"
jf-aap = { features=["std"], git = "ssh://git@github.com/SpectrumXYZ/jellyfish-apps.git" }
serde = { version = "1.0", features = ["derive"] }
serde_with = "1.10.0"
snafu = { version = "0.6.10", features = ["backtraces"] }
