name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Outdated Builds
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          all_but_latest: true
          access_token: ${{ github.token }}

      - name: Checkout Repository
        uses: actions/checkout@v3



      - name: Enable Rust Caching
        uses: Swatinem/rust-cache@v2

      - name: Format Check
        run: cargo fmt -- --check

      - name: Clippy
        run: |
          cargo clippy --workspace -- -D warnings

      - name: Audit
        run: cargo audit

      - name: Test
        run: |
          cargo test --workspace --release --no-run
          cargo test --workspace --release --verbose -- --test-threads 2
        timeout-minutes: 30
